version: '3.8'

services:
  app:
    build:
      context: .
      target: app
    command: pnpm --filter app run start
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - ORIGIN=${ORIGIN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DB_URL=${DB_URL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - '7149:3000'
    depends_on:
      - redis
      - db

  worker:
    build:
      context: .
      target: worker
    command: pnpm --filter workers run start
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=kLSN22t5MJs7fAfSjiBG
      - POSTGRES_DB=clairvue
    ports:
      - '5432:5432'

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '8081:8081'
    depends_on:
      - redis
