version: '3.8'

services:
  app:
    build: .
    command: pnpm run start
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - ORIGIN=${ORIGIN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DB_URL=${DB_URL}
    ports:
      - '7149:3000'
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=kLSN22t5MJs7fAfSjiBG
      - POSTGRES_DB=clairvue
    ports:
      - '5432:5432'

  migrations:
    build: .
    command: pnpm run migrate
    environment:
      - DB_URL=${DB_URL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
